### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by frequency81** [TV-Encryption/FairplayKSM#1]
when use command "cmake ."  is show error. How to fix?

-- Found Python: /usr/bin/python3.9 (found suitable version "3.9.12", minimum required is "3.8") found components: Development Interpreter
CMake Error at CMakeLists.txt:34 (install):
  install TARGETS given no LIBRARY DESTINATION for module target
  "FairplayKSM".

CMake Error at CMakeLists.txt:35 (install):
  install FILES given no DESTINATION!

-- Configuring incomplete, errors occurred!
See also "/home/fps/docker/FairplayKSM/CMakeFiles/CMakeOutput.log".

**Comment by cleverer** [comment]
Hi there 👋 

Just a side note: this project is not actively maintained, so it might be broken and not actively fixed (See https://github.com/TV-Encryption/Documents)

Could you also post the content of `/home/fps/docker/FairplayKSM/CMakeFiles/CMakeOutput.log`?
I'm no expert, maybe cmake got an update, which bricks the config…

Just to be sure, did you follow the instructions in the readme and add the files from Apples HLS demo as described?

**Comment by cleverer** [comment]
As no more info was provided, I'm closing this issue.
